### ISSUE TITLE
React component for program

### ISSUE THREAD

**Issue by MatthiasSaihttam** [OurJSEditor/OurJSEditor#104]
We need to rewrite the user profile page and program list with a better design, pagination, and React (#83). Before that happens, it would be nice to have a React component (and CSS) for a Program that we could drop in different places.
It would need to display the program name, thumbnail, author (maybe optionally), maybe if the program is published, and vote counts.

**Comment by MatthiasSaihttam** [comment]
Do you think this is something you could do if you get a chance in the next couple of weeks, @EthanLuisMcDonough?

**Comment by EthanLuisMcDonough** [comment]
Sure, I'll give it a go.

**Comment by MatthiasSaihttam** [comment]
@EthanLuisMcDonough Did you ever end up doing anything with this?

**Comment by EthanLuisMcDonough** [comment]
@MatthiasSaihttam I'm afraid not.  If my activity chart is any indication, I've been running low on inspiration as far as recreational programming goes.

**Comment by MatthiasSaihttam** [comment]
Fair enough. I'll get started on it. If you want to save me from doing CSS or React, you can always add commits to the program-list branch.
