### ISSUE TITLE
CSS for forgot password and reset password pages

### ISSUE THREAD

**Issue by MatthiasSaihttam** [OurJSEditor/OurJSEditor#118]
The Forgot password and Reset password pages need have CSS added to match the rest of the website.

**Comment by drwm-base** [comment]
Hi Matthias, can I work on this issue?

**Comment by MatthiasSaihttam** [comment]
Of course! The [Forgot Password](https://ourjseditor.com/user/forgot-password) page ([code](https://github.com/OurJSEditor/OurJSEditor/blob/master/django_code/account/templates/account/forgotPassword.html)) needs some love and CSS, anything there helps. Maybe start with the Login page design and remove/add rules as necessary. Similarly, the [Reset Password](https://ourjseditor.com/user/reset-password) page needs CSS, although it probably also needs React to let you know if the passwords don't match.
Let me know if you have trouble with the build instructions in the Readme. Having a full, local setup makes developing much more satisfying.

**Comment by drwm-base** [comment]
Hi Matthias, a few questions. For the Forgot Password page, which login page would you like me to base it on? There are several components labeled login, as well as the login.html in the same folder as the Forgot Password page. I'm unsure which one you want me to base it on?

**Comment by MatthiasSaihttam** [comment]
Basically, the Reset Password page and the program comments should use React (and don't). And the Forgot Password, Reset Password, and Account Unauthorized pages need CSS (and currently have *none*). If there's overlap with the Reset Password page and the Forgot Password page, we can use React for both.

So at some point the Reset Password page needs the whole shebang. That's a .html template file that calls the bundled JS file, any styles, and any common code. As well, it will need a JSX file in entries, that will then load components from a JSX file in components.

I'm recommending you start with CSS for the 3 pages that don't have any, based on the login page CSS (just inspect element on the login page), and if you feel comfortable writing JSX, doing that for the Reset Password page. The comments that show up under programs probably deserve their own issue—that's a matter of removing and replacing the existing JS, and since it works, isn't my first priority.

**Comment by drwm-base** [comment]
Alright! Thanks for getting back to me so fast. I will get on that right away!

**Comment by MatthiasSaihttam** [comment]
@drwm-base Have you had a chance to make any progress on this?

**Comment by drwm-base** [comment]
Hey Matthias, sorry about that. I can't work on this right now, other things came up. I'm sorry I completely forgot about this.

**Comment by MatthiasSaihttam** [comment]
No problem. I'll consider the issue up for grabs, but if you get a chance, contributions are appreciated.

**Comment by MatthiasSaihttam** [comment]
This issue used to mention re-doing comments. I've split that off into a new issue, #177.

**Comment by MatthiasSaihttam** [comment]
In progress work, courtesy of BCZ, here: https://ourjseditor.com/program/Qch6gM
