### ISSUE TITLE
Move user info popup to top

### ISSUE THREAD

**Issue by MatthiasSaihttam** [OurJSEditor/OurJSEditor#121]
There was some discussion in the Discord of moving the user-info bar back up to the top. The idea is growing on me, but I'm still interested in gaining feedback on this.

**Comment by birdofblue** [comment]
Having user info, navigation, and such all in one bar at the top seems pretty standard on lots of websites, (Github, Google, Khan Academy, etc.) so doing the same could make it easier for new users to get around.
