### ISSUE TITLE
Publish button does not work

### ISSUE THREAD

**Issue by birdofblue** [OurJSEditor/OurJSEditor#146]
I tried publishing a program recently, no thumbnail showed in the publish dialog, and the publish button didn't work (and had no event listener attached to it). It seems like the top window isn't getting the thumbnail data.

**Comment by MatthiasSaihttam** [comment]
Should be fixed, thanks for the report.

**Comment by birdofblue** [comment]
It seems like this hasn't been pushed to the production site yet. Is that coming soon?

**Comment by MatthiasSaihttam** [comment]
Seems to be working without issue for me. It may be a cacheing issue. (You can temporarily disable cache using the checkbox in the network settings of your browser's debugging tools.)

**Comment by birdofblue** [comment]
Sure enough, working now. Thanks!
