### ISSUE TITLE
Width on .vote-button should be a bit bigger

### ISSUE THREAD

**Issue by MatthiasSaihttam** [OurJSEditor/OurJSEditor#159]
Using a slightly non-standard, but by no means unreasonable sans-serif font, the text wraps to 2 lines. Just 150px would fix this.

**Comment by cenation007** [comment]
Hello @MatthiasSaihttam I would like to fix this issue. Reply to me if you have read my message

**Comment by MatthiasSaihttam** [comment]
@cenation007 Yep, I'm alive.

Off the top of my head, the relevant CSS file is at /django_code/program/static/program.css

**Comment by cenation007** [comment]
Its width is 140px right now, shall I make it to 170px?
