### ISSUE TITLE
Console not catching unhandled promise errors

### ISSUE THREAD

**Issue by MatthiasPortzel** [OurJSEditor/OurJSEditor#170]
This can be fixed with a `frame.contentWindow.addEventListener("unhandledrejection",`.

This is a annoying problem, because all P5.js code in the `setup` function is wrapped in a promise.

**Comment by MatthiasSaihttam** [comment]
Chrome is annoying. On Chrome, it's not possible to report the line or col number of an unhandled rejection. It is on Firefox. I'm going to have to do some annoying conditional to handle both cases.

**Comment by smj-edison** [comment]
I don't know if there is a way to get line numbers ever with promises. I think since the `reject` function can be moved all over the place it's impossible for the browser to pinpoint where the promise actually rejects at...
