### ISSUE TITLE
Uh, who hosts this again?

### ISSUE THREAD

**Issue by raumaankidwai** [OurJSEditor/OurJSEditor#18]
Because the public IP is listed here https://github.com/OurJSEditor/OurJSEditor/blob/e3799b1001e5104fe8f25bb388f8f3f1d1b9012b/django_code/ourjseditor/settings.py#L30, exposing their location.

**Comment by MatthiasSaihttam** [comment]
I'm [paying for hosting](https://linode.com), not doing it off of my own computer. I think I properly have the log files and other similar information out of version control.

**Comment by raumaankidwai** [comment]
😌
