### ISSUE TITLE
The hint system we have right now isn't errorring on ES6 but ES6 doesn't work

### ISSUE THREAD

**Issue by raumaankidwai** [OurJSEditor/OurJSEditor#19]
It's all in the title.

**Comment by raumaankidwai** [comment]
Wait, this is probably (definitely) browser-specific (I'm on a browser that doesn't support ES6), so let's change this to "The hint system should detect whether ES6 is supported on the user's browser."

**Comment by MatthiasSaihttam** [comment]
I think we should leave it up the user code to support or not support ES6. We would have to warn the user, basically, you're using ES6 features, your code might not run on all browsers. It seems like it would be a pain to maintain.
