### ISSUE TITLE
Better error pages

### ISSUE THREAD

**Issue by MatthiasSaihttam** [OurJSEditor/OurJSEditor#68]
We don't have a good 404 page right now, and the program and user not-found pages are also terrible looking.
For example: https://ourjseditor.com/program/ourjse, https://ourjseditor.com/user/ourjse

**Comment by MatthiasSaihttam** [comment]
Thanks! I think I need to add some code to the views.py files to render a template, but if you want to make a PR you can add a file at django_code/program/templates/404.html for programs. 
Let me know if you come up with some HTML/CSS, and then we can work together to make sure it ends up in the website.

**Comment by win32prog** [comment]
Ahh okay that makes sense, I was gonna ask about it. I'll put  the 404 page in another branch when I put something together. 😅

**Comment by win32prog** [comment]
Hey I created some html and css. I tried to make it look like the home page but, with a 404 message as the blog post. It still needs to be polished(github and discord link isn't links and arn't centered, missing aqua line on the post). Heres the html and css. 
[404.zip](https://github.com/OurJSEditor/OurJSEditor/files/2792504/404.zip)

**Comment by MatthiasSaihttam** [comment]
Thanks for your contribution, @win32prog, I just added your code (with some tweaks) to the website. Rather than try to make the Github and Discord links look good I just removed them (they only really need to be on the main page), and added some links in the body of the message. I added you as a co-author on the commit.
