### ISSUE TITLE
Database doesn't support unicode values

### ISSUE THREAD

**Issue by MatthiasSaihttam** [OurJSEditor/OurJSEditor#89]
The backend database right now is return ASCII encoding values, so we get a funky error when trying to save programs/nicknames/anything with any characters above ASCII (above 127).
The mysql database config needs to be switched to utf-8; I think Django will handle it fine.

**Comment by MatthiasSaihttam** [comment]
Took another stab at this again without success. I think the whole database needs to be exported and imported with the corrected encoding. Possible, but a pain.

**Comment by lukekrikorian** [comment]
You can retro-actively convert a MySQL DB to utf8 encoding without exporting and importing it (I am _fairly_ certain of this) https://github.com/lukekrikorian/rigby/blob/master/schema.sql might provide some insight

**Comment by MatthiasSaihttam** [comment]
I had looked into doing that earlier, but ran into foreign key errors. Just now I got it to update the tables by turning foreign key checks off. It appears to have updated the tables (`SHOW CREATE TABLE` shows a chatset of utf8mb4), and nothing appears broken, but I still can’t include high char point characters. 
I might need to update individual columns, or I’m still considering reloading the table data. I don’t have more time to work on it today, but I’m not out of options.

**Comment by MatthiasSaihttam** [comment]
Unless I'm mistaken (I'm which case everything is very messed up and I just didn't realize), I was actually using the correct `utf8mb4` charset on all my tables, if not from the beginning, for a while. I had to specify that in the settings.py options for Django to pick up on it, however.

Checked with:
```sql
SELECT table_name,column_name,character_set_name FROM information_schema.`COLUMNS` WHERE table_schema = "ourjseditor";
```
